### ISSUE TITLE
Once an album is published, no new item can be added

### ISSUE THREAD

**Issue by fsajp** [imeji-community/imeji#1057]
When an album is published, user can no longer make album active, and thus can no longer add items to the album anymore. 
We think that it would be better if user is still able to add items to album even though it has been published. 
(Perhaps by enable reverting the album status back to private if user want to edit the album?)

**Comment by fsajp** [comment]
Same request has been submitted earlier #546

**Comment by natasab** [comment]
This is fixed with the last community release. Please update your software version or integrate the changes.

**Comment by fsajp** [comment]
Can you please let us know in which version is this change already incorporated?
We tried version 2.0.0.0 and imeji-2.0.0.1-20140701.084715-3.war
But we still cannot add items on published album.
